<?php
/* Air2Java
 * (c)2014 Rom1
 */

?>
<h1>Welcome!</h1>

<p class="p">Welcome to the NetBeans PHP IDE sample - <b>TODO List application</b>.</p>
<p class="p">
    This sample does not use any PHP framework, it will show you possibilities how to:</p>
    <ul>
    <li>prevent public access to your scripts</li>
    <li>config your application</li>
    <li>access your database data</li>
    <li>change your database data (with redirect-after-post pattern)</li>
    <li>validate your data</li>
    <li>split scripts and templates</li>
    <li>handle expected and unexpected exceptions</li>
    </ul>
<p class="p">Detailed information can be found in the <i>readme.html</i> file.</p>
<p class="p"><b>This sample is not intented to be used on a production server without any changes.</b></p>
